[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["sharp", "ffmpeg-static"]
  included_files = ["node_modules/ffmpeg-static/ffmpeg"]

[[headers]]
  for = "/app-icon.png"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
